-- AlterTable
ALTER TABLE "SaleTemp" ADD COLUMN     "foodId" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "qty" INTEGER NOT NULL DEFAULT 1;

-- AddForeignKey
ALTER TABLE "SaleTemp" ADD CONSTRAINT "SaleTemp_foodId_fkey" FOREIGN KEY ("foodId") REFERENCES "Food"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
